
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ALLAH ALRAHEEM ALRAHMAN BISMphrase : BISM ALLAH ALRAHMAN ALRAHEEM'
    
_lr_action_items = {'BISM':([0,],[2,]),'$end':([1,5,],[0,-1,]),'ALLAH':([2,],[3,]),'ALRAHMAN':([3,],[4,]),'ALRAHEEM':([4,],[5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'phrase':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> phrase","S'",1,None,None,None),
  ('phrase -> BISM ALLAH ALRAHMAN ALRAHEEM','phrase',4,'p_phrase','py.py',29),
]
